#!/usr/bin/env python3
"""
WAVE Living Patterns Pipeline — SCAN Runner
Reads LP Proposal Issue, runs SCAN analysis via Anthropic API, posts result as comment.
Triggered by 'approved' label on Issue.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from lp_common import *

# ---------------------------------------------------------------------------
# SCAN Prompt Template
# ---------------------------------------------------------------------------

SCAN_PROMPT = """You are an expert in solution architecture, implementation analysis, and the specific domain described below. Your task is to perform a SCAN — a comprehensive implementation terrain reconnaissance for an AI-powered solution in this domain.

SCAN is a tool from the WAVE methodology (Workflow Amplification via Vectored Expertise). Its goal: identify the MOST IMPORTANT areas requiring deep analysis to build a high-quality Living Pattern (a living knowledge document) for this domain.

**IMPORTANT — Web search:** USE your web search tool actively. Search for:
- Current state of AI adoption in this domain (2025-2026 data)
- Regulatory requirements and compliance standards
- Leading solutions and platforms already operating
- Recent research papers and industry reports
- Known failures and lessons learned

Do NOT rely only on training data. Search the web for current information.

---

## SOLUTION CONTEXT

**Domain:** {domain}
**Specific area:** {area}
**Problem being addressed:** {problem}
**Proposed AI-powered solution:** {solution}

**Full proposal context:**
{proposal_body}

---

## YOUR TASK — TWO-STAGE SELECTION

### STAGE 1: Wide Exploration (8-10 candidates)

Think broadly across ALL dimensions: technology, architecture, data, regulation, compliance, human factors, change management, economics, ROI, ethics, bias, security, privacy, operations, integration, training, scaling.

List 8-10 candidate implementation areas. For each, write ONE sentence describing what it covers.

### STAGE 2: Scoring and Selection (top 5-6)

Score each candidate on THREE axes (1-10):

1. **Impact on objective function** — How directly does this area affect the success of the solution?
2. **Risk of omission** — What happens if we DON'T research this area? How dangerous is the gap?
3. **Knowledge availability** — Does sufficient research, case studies, and expert knowledge exist to build a quality Living Pattern?

Calculate total score = Impact + Risk + Availability. Rank all candidates. Select top 5-6 for detailed description. Show the full scoring table including eliminated candidates.

Then select ONE area as PRIMARY — the highest-scoring one — for immediate PULSE execution.

## OUTPUT FORMAT

Write in English. Use Markdown.

# SCAN: {domain} — Implementation Terrain Map

## Summary
[2-3 sentences: how many areas explored, how many selected, key dependencies, recommended focus]

## Stage 1: Candidate Areas (8-10)

| # | Candidate Area | One-Sentence Description |
|---|---------------|-------------------------|
| 1 | ... | ... |
| ... | ... | ... |

## Stage 2: Scoring

| # | Area | Impact (1-10) | Risk of Omission (1-10) | Knowledge Available (1-10) | Total | Selected |
|---|------|:------------:|:----------------------:|:-------------------------:|:-----:|:--------:|
| 1 | ... | 9 | 8 | 7 | 24 | ✅ |
| 2 | ... | 7 | 6 | 5 | 18 | ❌ |
| ... | ... | ... | ... | ... | ... | ... |

## Selected Areas (detailed)

### PRIMARY: [Area Name]
**Objective function:** [one sentence]
**Total score:** [X/30]
**Why primary:** [1-2 sentences based on scoring]

**Key research questions:**
1. ...
2. ...
3. ...
4. ...
5. ...

**PULSE Parameters (ready to use):**
```
AREA: [area name]
OBJECTIVE_FUNCTION: [objective function]
CONTEXT: AI-powered solution for {domain} — {area}. {solution}
CONSTRAINTS: Public knowledge only, no internal materials. Focus on current state of art (2025-2026), regulatory landscape, proven approaches and emerging innovations.
```

## Other Selected Areas (for future PULSE runs)

For EACH remaining selected area provide the COMPLETE block below — no exceptions:

### [Area Name]
**Objective function:** [one sentence]
**Total score:** [X/30]

**Key research questions:**
1. ...
2. ...
3. ...

**PULSE Parameters (ready to use):**
```
AREA: [area name]
OBJECTIVE_FUNCTION: [objective function]
CONTEXT: [specific context for this area]
CONSTRAINTS: [relevant constraints]
```

## Eliminated Areas (with reasoning)
[For each eliminated candidate: name + why it scored lower + whether it might be relevant in future]

---
*Generated by WAVE SCAN | {today}*

## FORMATTING RULE

Write flowing prose — do NOT break sentences across lines. When citing research findings, integrate them into the paragraph naturally. Do not put quoted text on a separate line.

Wrong:
```
Research reveals a landscape where
70% of organizations will adopt AI
, yet compliance lags behind.
```

Correct:
```
Research reveals a landscape where 70% of organizations will adopt AI, yet compliance lags behind.
```

Every element you create must be complete. Tables: all cells filled. PULSE Parameters: provided for ALL selected areas.
"""

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    issue_number = int(os.environ["ISSUE_NUMBER"])
    log(f"{'='*60}")
    log(f"SCAN RUNNER — Issue #{issue_number}")
    log(f"{'='*60}")

    # 1. Read Issue
    issue = get_issue(issue_number)
    title = issue["title"]
    body = issue["body"] or ""
    log(f"Title: {title}")

    # 2. Parse domain info from title
    domain, area = parse_domain_from_title(title)
    log(f"Domain: {domain}")
    log(f"Area: {area}")

    # 3. Extract problem/solution from Issue body
    problem = ""
    solution = ""
    for line in body.split("\n"):
        line_clean = line.strip().strip("|").strip()
        if "problem" in line.lower() and ":" in line:
            idx = line.index(":")
            problem = line[idx+1:].strip().strip("|").strip()
        if "solution" in line.lower() and ":" in line and "proposed" in line.lower():
            idx = line.index(":")
            solution = line[idx+1:].strip().strip("|").strip()

    # Fallback: use body directly
    if not problem:
        problem = "(see full proposal below)"
    if not solution:
        solution = "(see full proposal below)"

    log(f"Problem: {problem[:100]}...")
    log(f"Solution: {solution[:100]}...")

    # 4. Check for corrections
    comments = get_issue_comments(issue_number)
    corrections = find_corrections(comments, "scan") if find_comment(comments, "scan") else []
    correction_text = ""
    if corrections:
        log(f"Found {len(corrections)} correction(s) — including in prompt")
        correction_text = "\n\n## CORRECTIONS FROM REVIEWER\nPlease incorporate these corrections:\n" + "\n".join(corrections)

    # 5. Build and send SCAN prompt
    from datetime import date
    today = date.today().isoformat()

    prompt = SCAN_PROMPT.format(
        domain=domain,
        area=area or domain,
        problem=problem,
        solution=solution,
        proposal_body=body[:4000],
        today=today,
    ) + correction_text

    client = get_anthropic_client()
    log("Calling API for SCAN analysis (with web search)...")
    result = call_api(client, prompt, model=SONNET, max_tokens=8000, use_web_search=True)
    log(f"SCAN complete: {len(result)} chars")

    # Cleanup markdown
    result = cleanup_markdown(result)

    # 6. Post EN result as comment
    marker = MARKERS["scan"]
    comment_body = f"""{marker}
## 🔍 SCAN Analysis

{result}

---
*Generated by WAVE Living Patterns Pipeline — SCAN Runner EN | {today}*
*Next step: review the analysis above. If approved, add label `scan-approved` to proceed to PULSE Round 1.*
*To request corrections: post a comment starting with "## Correction" or "## Korekta", then add label `redo-scan`.*
"""

    add_comment(issue_number, comment_body)
    log("SCAN EN posted.")

    # 7. Translate to Polish
    log(f"Pausing {RATE_LIMIT_PAUSE}s before SCAN translation...")
    import time
    time.sleep(RATE_LIMIT_PAUSE)

    log("Translating SCAN to Polish...")
    translate_prompt = TRANSLATE_PROMPT.format(document=result)
    result_pl = call_api(client, translate_prompt, model=SONNET, max_tokens=10000, use_web_search=False)
    result_pl = cleanup_markdown(result_pl)
    log(f"SCAN PL: {len(result_pl)} chars")

    comment_pl = f"""## 🔍 Analiza SCAN (Polski)

{result_pl}

---
*Wygenerowano przez WAVE Living Patterns Pipeline — SCAN Runner PL | {today}*
*Następny krok: przejrzyj analizę powyżej. Jeśli zatwierdzasz, dodaj label `scan-approved` żeby przejść do PULSE Runda 1.*
*Korekty: napisz komentarz zaczynający się od "## Korekta" i dodaj label `redo-scan`.*
"""

    add_comment(issue_number, comment_pl)
    add_label(issue_number, "scan-ready")
    log("SCAN PL posted. Label 'scan-ready' added.")
    log("SCAN RUNNER DONE.")


if __name__ == "__main__":
    main()
