#!/usr/bin/env python3
"""
WAVE Living Patterns Pipeline — SCAN Runner
Reads LP Proposal Issue, runs SCAN analysis via Anthropic API, posts result as comment.
Triggered by 'approved' label on Issue.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from lp_common import *

# ---------------------------------------------------------------------------
# SCAN Prompt Template
# ---------------------------------------------------------------------------

SCAN_PROMPT = """You are an expert in solution architecture, implementation analysis, and the specific domain described below. Your task is to perform a SCAN — a comprehensive implementation terrain reconnaissance for an AI-powered solution in this domain.

SCAN is a tool from the WAVE methodology (Workflow Amplification via Vectored Expertise). Its goal: identify the MOST IMPORTANT areas requiring deep analysis to build a high-quality Living Pattern (a living knowledge document) for this domain.

**IMPORTANT — Web search:** USE your web search tool actively. Search for:
- Current state of AI adoption in this domain (2024-2025 data)
- Regulatory requirements and compliance standards
- Leading solutions and platforms already operating
- Recent research papers and industry reports
- Known failures and lessons learned

Do NOT rely only on training data. Search the web for current information.

---

## SOLUTION CONTEXT

**Domain:** {domain}
**Specific area:** {area}
**Problem being addressed:** {problem}
**Proposed AI-powered solution:** {solution}

**Full proposal context:**
{proposal_body}

---

## YOUR TASK

Identify 3-5 key implementation/knowledge areas that a comprehensive Living Pattern for this solution must cover. Think broadly: technology, regulation, human factors, economics, ethics, operations.

For each area determine:

1. **Area name** — short, unambiguous
2. **Objective function** — one sentence: what we optimize, specific to THIS solution
3. **Priority** — Critical / Important / Desired
4. **Key research questions** — 3-5 specific questions the Living Pattern must answer
5. **Ready PULSE parameters** — pre-filled block for PULSE prompt

Then select ONE area as PRIMARY — the one with highest priority and strongest objective function — for immediate PULSE execution.

## OUTPUT FORMAT

Write in English. Use Markdown.

# SCAN: {domain} — Implementation Terrain Map

## Summary
[2-3 sentences: how many areas, key dependencies, recommended focus]

## Areas Overview
| # | Area | Priority | Objective Function |
|---|------|----------|--------------------|
| 1 | ... | Critical | ... |
| 2 | ... | ... | ... |

## Primary Area for PULSE

### [Area Name]
**Objective function:** [one sentence]
**Priority:** Critical
**Why primary:** [1-2 sentences]

**Key research questions:**
1. ...
2. ...
3. ...
4. ...
5. ...

**PULSE Parameters (ready to use):**
```
AREA: [area name]
OBJECTIVE_FUNCTION: [objective function]
CONTEXT: AI-powered solution for {domain} — {area}. {solution}
CONSTRAINTS: Public knowledge only, no internal materials. Focus on current state of art (2025-2026), regulatory landscape, proven approaches and emerging innovations.
```

## Other Areas (for future PULSE runs)

For EACH area provide the COMPLETE block below — no exceptions:

### [Area Name]
**Objective function:** [one sentence]
**Key research questions:**
1. ...
2. ...
3. ...

**PULSE Parameters (ready to use):**
```
AREA: [area name]
OBJECTIVE_FUNCTION: [objective function]
CONTEXT: [specific context for this area]
CONSTRAINTS: [relevant constraints]
```

## Areas Consciously Excluded
[If any areas were considered but excluded — list with reasoning]

---
*Generated by WAVE SCAN | {today}*

## FORMATTING RULE

Write flowing prose — do NOT break sentences across lines. When citing research findings,
integrate them into the paragraph naturally. Do not put quoted text on a separate line.

Wrong:
```
Research reveals a landscape where
70% of organizations will adopt AI
, yet compliance lags behind.
```

Correct:
```
Research reveals a landscape where 70% of organizations will adopt AI, yet compliance lags behind.
```

Every element you create must be complete. Tables: all cells filled. PULSE Parameters: provided for ALL areas, not just primary.
"""

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    issue_number = int(os.environ["ISSUE_NUMBER"])
    log(f"{'='*60}")
    log(f"SCAN RUNNER — Issue #{issue_number}")
    log(f"{'='*60}")

    # 1. Read Issue
    issue = get_issue(issue_number)
    title = issue["title"]
    body = issue["body"] or ""
    log(f"Title: {title}")

    # 2. Parse domain info from title
    domain, area = parse_domain_from_title(title)
    log(f"Domain: {domain}")
    log(f"Area: {area}")

    # 3. Extract problem/solution from Issue body
    problem = ""
    solution = ""
    for line in body.split("\n"):
        line_clean = line.strip().strip("|").strip()
        if "problem" in line.lower() and ":" in line:
            idx = line.index(":")
            problem = line[idx+1:].strip().strip("|").strip()
        if "solution" in line.lower() and ":" in line and "proposed" in line.lower():
            idx = line.index(":")
            solution = line[idx+1:].strip().strip("|").strip()

    # Fallback: use body directly
    if not problem:
        problem = "(see full proposal below)"
    if not solution:
        solution = "(see full proposal below)"

    log(f"Problem: {problem[:100]}...")
    log(f"Solution: {solution[:100]}...")

    # 4. Check for corrections
    comments = get_issue_comments(issue_number)
    corrections = find_corrections(comments, "scan") if find_comment(comments, "scan") else []
    correction_text = ""
    if corrections:
        log(f"Found {len(corrections)} correction(s) — including in prompt")
        correction_text = "\n\n## CORRECTIONS FROM REVIEWER\nPlease incorporate these corrections:\n" + "\n".join(corrections)

    # 5. Build and send SCAN prompt
    from datetime import date
    today = date.today().isoformat()

    prompt = SCAN_PROMPT.format(
        domain=domain,
        area=area or domain,
        problem=problem,
        solution=solution,
        proposal_body=body[:4000],
        today=today,
    ) + correction_text

    client = get_anthropic_client()
    log("Calling API for SCAN analysis (with web search)...")
    result = call_api(client, prompt, model=SONNET, max_tokens=4000, use_web_search=True)
    log(f"SCAN complete: {len(result)} chars")

    # Cleanup markdown
    result = cleanup_markdown(result)

    # 6. Post EN result as comment
    marker = MARKERS["scan"]
    comment_body = f"""{marker}
## 🔍 SCAN Analysis

{result}

---
*Generated by WAVE Living Patterns Pipeline — SCAN Runner EN | {today}*
*Next step: review the analysis above. If approved, add label `scan-approved` to proceed to PULSE Round 1.*
*To request corrections: post a comment starting with "## Correction" or "## Korekta", then add label `redo-scan`.*
"""

    add_comment(issue_number, comment_body)
    log("SCAN EN posted.")

    # 7. Translate to Polish
    log(f"Pausing {RATE_LIMIT_PAUSE}s before SCAN translation...")
    import time
    time.sleep(RATE_LIMIT_PAUSE)

    log("Translating SCAN to Polish...")
    translate_prompt = TRANSLATE_PROMPT.format(document=result)
    result_pl = call_api(client, translate_prompt, model=SONNET, max_tokens=6000, use_web_search=False)
    result_pl = cleanup_markdown(result_pl)
    log(f"SCAN PL: {len(result_pl)} chars")

    comment_pl = f"""## 🔍 Analiza SCAN (Polski)

{result_pl}

---
*Wygenerowano przez WAVE Living Patterns Pipeline — SCAN Runner PL | {today}*
*Następny krok: przejrzyj analizę powyżej. Jeśli zatwierdzasz, dodaj label `scan-approved` żeby przejść do PULSE Runda 1.*
*Korekty: napisz komentarz zaczynający się od "## Korekta" i dodaj label `redo-scan`.*
"""

    add_comment(issue_number, comment_pl)
    add_label(issue_number, "scan-ready")
    log("SCAN PL posted. Label 'scan-ready' added.")
    log("SCAN RUNNER DONE.")


if __name__ == "__main__":
    main()
